controller_manager:
  ros__parameters:
    update_rate: 30
    #use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:
    type        : diff_drive_controller/DiffDriveController
    use_stamped_vel: false
    right_wheel_names: ['wheel_right_joint']
    left_wheel_names: ['wheel_left_joint']
        
    publish_rate: 50.0
    pose_covariance_diagonal : [0.001, 0.001, 1.0e-3, 1.0e-3, 1.0e-3, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 1.0e-3, 1.0e-3, 1.0e-3, 0.01]
    
    wheel_separation: 0.237
    wheel_radius: 0.033
  
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    cmd_vel_timeout: 0.5
    base_frame_id: base_footprint # default : base_link
    publish_limited_velocity: true
    publish_wheel_data: true
    enable_odom_tf: false

    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 0.7  # m/s
        min_velocity           : -0.7 # m/s
        has_acceleration_limits: true
        max_acceleration       : 0.7  # m/s^2
        min_acceleration       : -0.7 # m/s^2
        has_jerk_limits        : false
        max_jerk               : 5.0  # m/s^3
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 8.5  # rad/s
        min_velocity           : -8.5  # rad/s
        has_acceleration_limits: true
        max_acceleration       : 5.0  # rad/s^2
        min_acceleration       : -5.0   # rad/s^2
        has_jerk_limits        : false
        max_jerk               : 2.5  # rad/s^3

# joint_broad:
#   ros__parameters:
