rplidar_node:
  ros__parameters:
    channel_type: serial
    serial_port: /dev/rplidar
    serial_baudrate: 460800
    frame_id: ldlidar_link
    inverted: false
    angle_compensate: true
    scan_mode: Standard
